# Generated by Django 4.1.1 on 2022-09-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('game_description', models.TextField(max_length=500)),
                ('game_image', models.ImageField(blank=True, upload_to='game_image')),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=25)),
                ('countries', models.CharField(help_text='E.g. Enter: NP vs JPN', max_length=200)),
                ('score_description', models.TextField(max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamescategory')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_title', models.CharField(max_length=255)),
                ('match_details', models.TextField(max_length=500)),
                ('schedule_img', models.ImageField(blank=True, upload_to='schedule_img')),
                ('for_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamescategory')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_title', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True)),
                ('of_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamescategory')),
            ],
        ),
    ]
